 XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/local/cuda python tof_nerf.py --config config/config_fast.txt \
    --dataset_type mitsuba \
    --scan $2 \
    --no_batching \
    --datadir $3 \
    --expname mitsuba_$2_$1_static_fast \
    --depth_range 15 --scene_scale 1.0 --bias_range 7.5 --falloff_range 4.0 \
    --num_views $1 \
    --num_frames $1 \
    --train_views $8 \
    --tof_image_width $6 --tof_image_height $7 \
    --color_image_width $6 --color_image_height $7 \
    --lrate 1e-3 --lrate_calib 1e-3 --lrate_decay 250 --lrate_decay_calib 100 \
    --tof_scale_factor 0.5 \
    --color_scale_factor 0.5 \
    --i_img 1000 \
    --i_weights 10000 \
    --i_video 10001 \
    --geometry_pass_iters 1000000 \
    --direct_pass_iters 0 \
    --shading_normal_iters 0 \
    --i_aux 10000000 \
    --use_depth_sampling \
    --min_depth_fac 0.05 --max_depth_fac 0.5 \
    --use_phasor --no_phase_training --no_phase_iters 50000  \
    --view_step 1 --view_start $4 --total_num_views $5 \
    --optimize_poses --pose_reg_weight 0.0 --use_relative_poses --colocated_pose \
    --static_scene_iters 5000 --calibration_pretraining \
    --model_reset_iters 5000 --reset_static_model \
    --tof_weight 8.0 --tof_weight_decay 0.01 --tof_weight_decay_steps 100 \
    --radiance_weight 2.0 --no_radiance_iters 0 \